// utils/params.ts

export const params = [
  // CURRENT
  'Genset_L1_Current',
  'Genset_L2_Current',
  'Genset_L3_Current',
  'Genset_Avg_Current',
  'Phase-A Share',
  'Phase-B Share',
  'Phase-C Share',
  'Neutral_Current',
  'Current_Imbalance',
  'Genset_Application_Nominal_Current_PC2X',
  'Genset_Standby_Nominal_Current_PC2X',

  // VOLTAGE
  'Genset_L1L2_Voltage',
  'Genset_L2L3_Voltage',
  'Genset_L3L1_Voltage',
  'Genset_LL_Avg_Voltage',
  'Genset_L1N_Voltage',
  'Genset_L2N_Voltage',
  'Genset_L3N_Voltage',
  'Genset_LN_Avg_Voltage',
  'Voltage_Imbalance',
  'Nominal_Battery_Voltage',
  'Battery_Voltage_calculated',

  // POWER
  'Genset_L1_kW',
  'Genset_L2_kW',
  'Genset_L3_kW',
  'Genset_Total_kW',
  'Genset_Standby_kW_Rating_PC2X',
  'Genset_Application_kW_Rating_PC2X',
  'Genset_L1_kVA',
  'Genset_L2_kVA',
  'Genset_L3_kVA',
  'Genset_Total_kVA',
  'Genset_Standby_kVA_Rating_PC2X',
  'Genset_Application_kVA_Rating_PC2X',
  'Genset_L1_kVAR',
  'Genset_L2_kVAR',
  'Genset_L3_kVAR',
  'Genset_Total_kVAR',

  // TEMPERATURE
  'Coolant_Temperature',
  'Oil_Temperature',
  'Intake_Manifold_Temperature_calculated',
  'Cooling_Margin',
  'OTSR',

  // PRESSURE
  'Barometric_Absolute_Pressure',
  'Boost_Pressure',
  'Fuel_Outlet_Pressure_calculated',
  'Oil_Pressure',

  // FUEL
  'Fuel_Consumption',
  'Fuel_Flow_Change',
  'Fuel_Rate',
  'Fuel_Efficiency_Index',
  // 'Specific_Fuel_Consumption',
  // 'Total_Fuel_Consumption_Calculated',

  // OTHER
  'Genset_L1_Power_Factor_PC2X',
  'Genset_L2_Power_Factor_PC2X',
  'Genset_L3_Power_Factor_PC2X',
  'Genset_Total_Power_Factor_calculated',
  'Power_Loss_Factor',
  'Base_Frequency_calculated',
  'Genset_Frequency_OP_calculated',
  'Air_Fuel_Effectiveness',
  'Averagr_Engine_Speed',
  'RPM_Stability_Index',
  'Engine_Running_Time_calculated',
  'Percent_Engine_Torque_or_Duty_Cycle',
  'Genset_Run_SS',
  'Heat_Rate',
  'Load_Percent',
  'Lubrication_Risk_Index',
  'Mechanical_Stress_Index',
  'Load_Stress_Index',
  'Thermal_Stress_Index',
  'Electrical_Stress_Index',
  'Oscillation_Index',
  // 'VHz_Knee_Frequency',
  // 'VHz_Rolloff_Slope',
  'I2 Heating',
  'Thermal_Efficiency',
];
