// utils/params.ts

export const params = [
  // CURRENT
  'Genset_L1_Current',
  'Genset_L2_Current',
  'Genset_L3_Current',
  'Genset_Avg_Current',
  'Phase-A Share',
  'Phase-B Share',
  'Phase-C Share',
  'Neutral_Current',
  'Current_Imbalance',
  'Genset_Application_Nominal_Current_PC2x',
  'Genset_Standby_Nominal_Current_PC2x',

  // VOLTAGE
  'Genset_L1L2_Voltage',
  'Genset_L2L3_Voltage',
  'Genset_L3L1_Voltage',
  'Genset_LL_Avg_Voltage',
  'Genset_L1N_Voltage',
  'Genset_L2N_Voltage',
  'Genset_L3N_Voltage',
  'Genset_LN_Avg_Voltage',
  'Voltage_Imbalance',
  'Nominal_Battery_Voltage',
  'Battery_Voltage_Calculated',

  // POWER
  'Genset_L1_KW',
  'Genset_L2_KW',
  'Genset_L3_KW',
  'Genset_Total_KW',
  'Genset_Standby_KW_Rating_PC2x',
  'Genset_Application_KW_Rating_PC2x',
  'Genset_L1_KVA',
  'Genset_L2_KVA',
  'Genset_L3_KVA',
  'Genset_Total_KVA',
  'Genset_Standby_KVA_Rating_PC2x',
  'Genset_Application_KVA_Rating_PC2x',
  'Genset_L1_KVAR',
  'Genset_L2_KVAR',
  'Genset_L3_KVAR',
  'Genset_Total_KVAR',

  // TEMPERATURE
  'Coolant_Temperature',
  'Oil_Temperature',
  'Intake_Manifold_Temperature',
  'Cooling_Margin',
  'Oil_Temperature_Safety_Ratio',

  // PRESSURE
  'Barometric_Absolute_Pressure',
  'Boost_Pressure',
  'Fuel_Outlet_Pressure_Calculated',
  'Oil_Pressure',

  // FUEL
  'Fuel_Consumption',
  'Fuel_Flow_Change',
  'Fuel_Rate',
  'Specific_Fuel_Consumption',
  'Fuel_Efficiency_Index',
  'Total_Fuel_Consumption_Calculated',

  // OTHER
  'Genset_L1_Power_Factor_PC2x',
  'Genset_L2_Power_Factor_PC2x',
  'Genset_L3_Power_Factor_PC2x',
  'Genset_Total_Power_Factor_Calculated',
  'Power_Loss_Factor',
  'Base_Frequency_Calculated',
  'Genset_Frequency_OP_Calculated',
  'Air_Fuel_Effectiveness',
  'Average_Engine_Speed',
  'RPM_Stability_Index',
  'Engine_Running_Time_Calculated',
  'Percent_Engine_Torque_or_Duty_Cycle',
  'Genset_Run_SS',
  'Heat_Rate',
  'Load_Percent',
  'Lubrication_Risk_Index',
  'Mechanical_Stress',
  'Load_Stress',
  'Thermal_Stress',
  'Electrical_Stress',
  'Oscillation_Index',
  'VHz_Knee_Frequency',
  'VHz_Rolloff_Slope',
  'I2 Heating',
  'Thermal_Efficiency',
];
